stages:
  - build
  - deploy
  - verify

variables:
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  GIT_SUBMODULE_STRATEGY: normal

internal:
  tags:
    - ios_internal
  stage: build
  only:
    - master
  except:
    - tags
  script:
    - bash buildbox/build-telegram.sh hockeyapp
    - bash buildbox/deploy-telegram.sh hockeyapp
  environment:
    name: internal

beta_testflight:
  tags:
    - ios_beta
  stage: build
  only:
    - beta
  except:
    - tags
  script:
    - bash buildbox/build-telegram.sh appstore
  environment:
    name: testflight_llc
  artifacts:
    paths:
      - build/artifacts
    expire_in: 1 week

deploy_beta_testflight:
  tags:
    - ios_beta
  stage: deploy
  only:
    - beta
  except:
    - tags
  script:
    - bash buildbox/deploy-telegram.sh appstore
  environment:
    name: testflight_llc

verify_beta_testflight:
  tags:
    - ios_beta
  stage: verify
  only:
    - beta
  except:
    - tags
  script:
    - bash buildbox/verify-telegram.sh appstore
  environment:
    name: testflight_llc
