language: objective-c
before_install:
- gem install xcpretty -N cocoapods
script:
- set -o pipefail
- cd Support
- xcodebuild -project HockeySDK.xcodeproj -scheme "HockeySDK" -sdk iphonesimulator
  -configuration Debug -destination "platform=iOS Simulator,name=iPhone 6" test |
  xcpretty -c
- xcodebuild -project HockeySDK.xcodeproj -scheme "HockeySDK Framework" -sdk iphonesimulator
  -configuration Debug -destination "platform=iOS Simulator,name=iPhone 6" test |
  xcpretty -c
- cd ..
